name: image-build
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_REPO_NAME: rookiezoe/network-cabinet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "VERSION=$(date +%Y.%m.%d)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish to DockerHub
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.multiarch
          tags: ${{ env.DOCKER_REPO_NAME }}:latest,${{ env.DOCKER_REPO_NAME }}:${{ env.VERSION }}
          context: .
          platforms: linux/amd64,linux/arm64
